In [ ]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import scipy.stats as st





In [30]:
df = pd.read_csv("../bcancer.csv")
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [32]:
df.isnull().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [33]:
df.diagnosis.value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [35]:
class_p = df.diagnosis.value_counts(normalize=True)
class_p

diagnosis
B    0.627417
M    0.372583
Name: proportion, dtype: float64

In [ ]:
p_m = class_p['M']
p_b = class_p["B"]
p_m, p_b

(0.37258347978910367, 0.6274165202108963)

In [39]:
data1 = df[['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean']]
data1.head(2)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean
0         M        17.99         10.38           122.8     1001.0
1         M        20.57         17.77           132.9     1326.0

In [41]:
data_m = data1[data1.diagnosis == "M"]
data_b = data1[data1.diagnosis == "B"]

In [43]:
test = np.array([17.99, 10.38, 122.8, 1001.0])
test

array([  17.99,   10.38,  122.8 , 1001.  ])

In [69]:
prob_m = st.gaussian_kde(data_m["radius_mean"]).pdf(test[0]) * st.gaussian_kde(data_m["texture_mean"]).pdf(test[1]) * st.gaussian_kde(data_m["perimeter_mean"]).pdf(test[2]) *  st.gaussian_kde(data_m["area_mean"]).pdf(test[3]) * p_m
prob_m

array([1.29869883e-09])

In [70]:
prob_b = st.gaussian_kde(data_b["radius_mean"]).pdf(test[0]) * st.gaussian_kde(data_b["texture_mean"]).pdf(test[1]) * st.gaussian_kde(data_b["perimeter_mean"]).pdf(test[2]) *  st.gaussian_kde(data_b["area_mean"]).pdf(test[3]) * p_b
prob_b

array([1.00561393e-14])

In [71]:
if prob_m > prob_b:
    print("The test data belongs to maligant")
else:
    print("the test data belongs to benign")

The test data belongs to maligant


In [73]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

In [75]:
inp = df.drop(columns="diagnosis")
out = df.diagnosis

In [80]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(inp, out, test_size=0.3, random_state=48)

In [79]:
gnb = GaussianNB()
gnb.fit(xtrain, ytrain)

GaussianNB()

In [84]:
pred = gnb.predict(xtest)
pred

array(['B', 'M', 'M', 'M', 'B', 'M', 'B', 'M', 'M', 'M', 'B', 'B', 'M',
       'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B',
       'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M',
       'M', 'M', 'M', 'B', 'B', 'M', 'M', 'M', 'M', 'B', 'M', 'B', 'B',
       'M', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B',
       'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'M', 'B',
       'M', 'M', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M',
       'M', 'M', 'B', 'B', 'M', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'M',
       'M', 'M', 'M', 'M', 'M', 'B', 'M', 'M', 'M', 'B', 'M', 'M', 'M',
       'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'M', 'B',
       'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B',
       'B', 'M'], dtype='<U1')

In [82]:
# All input follow normal distrubution the use GaussianNB
# All input are boolean in nature then use BernoulliNB
# All input varibale are having frequency count the use MultinomialNB